In [5]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [9]:
def windowed_dataset(series, window_size, batch_size, shuffle_buffer):
    dataset = tf.data.Dataset.range(series)
    dataset = dataset.window(window_size+1, shift=1, drop_remainder=True) # windowed data, drop_remainder chops bottom of gen data and ensures same len
    dataset = dataset.flat_map(lambda window: window.batch(window_size + 1)) # MAPPING OPERATIONS
    dataset = dataset.shuffle(buffer_size=shuffle_buffer).map(lambda window: (window[:-1], window[-1:])) # SHUFFLING
    dataset = dataset.batch(batch_size).prefetch(1) # BATCHING
    return dataset
dataset = windowed_dataset(series=10, window_size=4, batch_size=4, shuffle_buffer=10)
for train,test in dataset:
    print(train.numpy(), test.numpy())

[[2 3 4 5]
 [5 6 7 8]
 [3 4 5 6]
 [4 5 6 7]] [[6]
 [9]
 [7]
 [8]]
[[1 2 3 4]
 [0 1 2 3]] [[5]
 [4]]
